Forum/forum/apps/threads/routes.py
from flask import redirect, url_for, flash, Blueprint, render_template, abort, request
from flask_login import login_required, current_user
from slugify import slugify
from .forms import ThreadCreationForm
from forum.database.models import Thread, Category
from forum.src.decorators.email_verified import email_verified
from sqlalchemy.orm import joinedload

thread_blueprint = Blueprint("threads", __name__, template_folder="templates")




@thread_blueprint.route("/create", methods=["GET", "POST"])
@login_required
@email_verified
def create():
    thread_form = ThreadCreationForm()

    if thread_form.validate_on_submit():
        title = thread_form.title.data
        category_id = thread_form.category_id.data
        content = thread_form.content.data
        user_id = current_user.id

        thread = Thread(title=title,
                        category_id=category_id,
                        content=content,
                        user_id=user_id,
                        slug=slugify(title),
                        views_count=0
                        )
        thread.save()

        flash("Your question has been posted successfully", "success")
        return redirect(url_for("main.index"))

    return render_template("threads/create.html", form=thread_form)


@thread_blueprint.route("<string:category_slug>")
def category_threads(category_slug):
    category = Category.query.filter_by(slug=category_slug).first_or_404()

    page = request.args.get('page', 1, type=int)

    threads = Thread.query\
                    .filter_by(category_id=category.id)\
                    .order_by(Thread.created_at.desc())\
                    .options(joinedload(Thread.category))\
                    .options(joinedload(Thread.comments))\
                    .paginate(page, 10, False)

    return render_template('main/index.html', threads=threads)



@thread_blueprint.route("<string:category_slug>/<string:thread_slug>", methods=["GET", "POST", "DELETE", "PUT"])
def show(category_slug, thread_slug):
    category = Category.query.filter_by(slug=category_slug).first_or_404()
    thread = Thread.query\
        .filter_by(category_id=category.id, slug=thread_slug)\
        .first_or_404()

    if request.method == "GET":
        thread.update({"views_count": thread.views_count + 1})

    if request.method == b"DELETE":
        if thread.is_owner(current_user):
            thread.delete()
            flash("Your question has been deleted successfully", "success")

            return redirect(url_for('main.index'))
        else:
            abort(403)
        
    if request.method == b"PUT":
        if thread.is_owner(current_user):
            thread.update({
                "title": request.form['title'],
                "slug": slugify(request.form['title']),
                "category_id": request.form['category_id'],
                "content": request.form['content']
            })

            flash("Your question has been updated successfully", "success")

            return redirect(url_for('threads.show', category_slug=thread.category.slug, thread_slug=thread.slug))
        else:
            abort(403)

    return render_template("threads/show.html", thread=thread)


@thread_blueprint.route("<string:category_slug>/<string:thread_slug>/edit")
@login_required
@email_verified
def edit(category_slug, thread_slug):

    category = Category.query.filter_by(slug=category_slug).first_or_404()
    thread = Thread.query.filter_by(category_id=category.id, slug=thread_slug).first_or_404()

    if not thread.is_owner(current_user):
        abort(403)

    thread_form = ThreadCreationForm()

    thread_form.title.data = thread.title
    thread_form.category_id.data = thread.category_id
    thread_form.content.data = thread.content
    thread_form.submit.label.text = "Edit"

    return render_template("threads/edit.html", thread=thread, form=thread_form)

Forum/forum/templates/layouts/partials/alert.html
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        <script>
            {% for category, message in messages %}
                {% if category == "success" %}
                    iziToast.success({
                        message: "{{ message }}",
                        position: "bottomRight"
                    });
                {% endif %}
                {% if category == "danger" %}
                    iziToast.error({
                        message: "{{ message }}",
                        position: "bottomRight"
                    });
                {% endif %}

                {% if category == "warning" %}

                    iziToast.warning({
                        message: "{{ message }}",
                        position: "bottomRight",
                    });
                {% endif %}

            {% endfor %}
        </script>
    {% endif %}
{% endwith %}

Forum/forum/templates/layouts/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light shadow-sm" style="background-color: rgba(239, 228, 212, 0.45) !important;;">
  <a class="navbar-brand" href="http://172.18.0.2:5000/">
    <img src="{{ url_for("static", filename="images/logo.png") }}" style="width: 100%; height: 55px" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item  dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="categories-dropdown" data-toggle="dropdown" style="color: #151618 !important">Categories <span class="sr-only">(current)</span></a>
        <div class="dropdown-menu dropdown-menu-left">
          {% for category in app_categories %}
          <a class="dropdown-item" href="{{  url_for('threads.category_threads', category_slug=category.slug) }}">
            {{ category.name }}
          </a>
          {% endfor %}
        </div>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('threads.create') }}" style="color: #151618 !important">New thread</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#" style="color: #151618 !important">Action</a>
          <a class="dropdown-item" href="{{  url_for('settings.index') }}" style="color: #151618 !important">
            <i class="la la-cogs"></i>
            Settings
          </a>
          <div class="dropdown-divider"></div>
          <form method="POST" action="{{ url_for("auth.logout") }}">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <button class="btn btn-white" type="submit" style="color: #151618 !important">Logout</button>
          </form>
        </div>
      </li>
      {% else %}
      <li class="nav-item pr-2">
        <a class="nav-link" href="{{ url_for('auth.login') }}" style="color: #151618 !important">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('auth.register') }}" style="color: #151618 !important">Register</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>