Forum/forum/apps/threads/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length
from forum.database.models import Category
from forum.src.utilities.helpers import cached_categories

try:
    categories_choices = [(category.get("id"), category.get("name")) for category in cached_categories()]
except:
    categories_choices = []



class ThreadCreationForm(FlaskForm):
    title = StringField("Question Title", validators=[DataRequired(), Length(max=100)])
    content = TextAreaField("Content", validators=[DataRequired(), Length(min=10)])
    category_id = SelectField("Category", validators=[DataRequired()], choices=categories_choices, coerce=int)
    submit = SubmitField("Create")

Forum/forum/apps/threads/routes.py
from flask import redirect, url_for, flash, Blueprint, render_template, abort, request
from flask_login import login_required, current_user
from slugify import slugify
from .forms import ThreadCreationForm
from forum.database.models import Thread, Category
from forum.src.decorators.email_verified import email_verified
from sqlalchemy.orm import joinedload

thread_blueprint = Blueprint("threads", __name__, template_folder="templates")




@thread_blueprint.route("/create", methods=["GET", "POST"])
@login_required
@email_verified
def create():
    thread_form = ThreadCreationForm()

    if thread_form.validate_on_submit():
        title = thread_form.title.data
        category_id = thread_form.category_id.data
        content = thread_form.content.data
        user_id = current_user.id

        thread = Thread(title=title,
                        category_id=category_id,
                        content=content,
                        user_id=user_id,
                        slug=slugify(title),
                        views_count=0
                        )
        thread.save()

        flash("Your question has been posted successfully", "success")
        return redirect(url_for("main.index"))

    return render_template("threads/create.html", form=thread_form)


@thread_blueprint.route("<string:category_slug>")
def category_threads(category_slug):
    category = Category.query.filter_by(slug=category_slug).first_or_404()

    page = request.args.get('page', 1, type=int)

    threads = Thread.query\
                    .filter_by(category_id=category.id)\
                    .order_by(Thread.created_at.desc())\
                    .options(joinedload(Thread.category))\
                    .options(joinedload(Thread.comments))\
                    .paginate(page, 10, False)

    return render_template('main/index.html', threads=threads)



@thread_blueprint.route("<string:category_slug>/<string:thread_slug>", methods=["GET", "POST", "DELETE", "PUT"])
def show(category_slug, thread_slug):
    category = Category.query.filter_by(slug=category_slug).first_or_404()
    thread = Thread.query\
        .filter_by(category_id=category.id, slug=thread_slug)\
        .first_or_404()

    if request.method == "GET":
        thread.update({"views_count": thread.views_count + 1})

    if request.method == b"DELETE":
        if thread.is_owner(current_user):
            thread.delete()
            flash("Your question has been deleted successfully", "success")

            return redirect(url_for('main.index'))
        else:
            abort(403)
        
    if request.method == b"PUT":
        if thread.is_owner(current_user):
            thread.update({
                "title": request.form['title'],
                "slug": slugify(request.form['title']),
                "category_id": request.form['category_id'],
                "content": request.form['content']
            })

            flash("Your question has been updated successfully", "success")

            return redirect(url_for('threads.show', category_slug=thread.category.slug, thread_slug=thread.slug))
        else:
            abort(403)

    return render_template("threads/show.html", thread=thread)


@thread_blueprint.route("<string:category_slug>/<string:thread_slug>/edit")
@login_required
@email_verified
def edit(category_slug, thread_slug):

    category = Category.query.filter_by(slug=category_slug).first_or_404()
    thread = Thread.query.filter_by(category_id=category.id, slug=thread_slug).first_or_404()

    if not thread.is_owner(current_user):
        abort(403)

    thread_form = ThreadCreationForm()

    thread_form.title.data = thread.title
    thread_form.category_id.data = thread.category_id
    thread_form.content.data = thread.content
    thread_form.submit.label.text = "Edit"

    return render_template("threads/edit.html", thread=thread, form=thread_form)

Forum/forum/apps/threads/templates/threads/create.html
{% extends "layouts/app.html" %}

{% block content %}
    <h4 class="mt-4">Ask your question</h4>
    <hr/>
    <form action="{{ url_for("threads.create") }}" method="POST">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-sm-12 col-lg-6 form-group">
                {{ form.title.label }}
                <div class="d-flex justify-content-end">
                    <small>Enter 50 characters or more.</small>
                </div>
                {{ form.title(class="form-control") }}
                {% for error in form.title.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="col-sm-12 col-lg-6 form-group">
                {{ form.category_id.label }}
                <div class="d-flex justify-content-end">
                    <small>Choose a category for your question</small>
                </div>
                {{ form.category_id(class="form-control custom-select") }}
                {% for error in form.category_id.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="col-12 form-group">
                {{ form.content.label }}
                <div class="d-flex justify-content-end">
                    <small>Write your full question here, including any relevant information.</small>
                </div>
                {{ form.content(class="form-control", rows=8) }}
                {% for error in form.content.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="col-12  form-group mt-4">
                {{ form.submit(class="btn btn-outline-primary w-100 btn-lg") }}
            </div>
        </div>
    </form>


{% endblock content %}

Forum/forum/apps/threads/templates/threads/edit.html
{% extends "layouts/app.html" %}

{% block content %}
    <h4 class="mt-4">Edit your question</h4>
    <hr/>
    <form action="{{ url_for("threads.show", category_slug=thread.category.slug, thread_slug=thread.slug) }}?_method=PUT" method="POST">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-sm-12 col-lg-6 form-group">
                {{ form.title.label }}
                <div class="d-flex justify-content-end">
                    <small>Enter 50 characters or more.</small>
                </div>
                {{ form.title(class="form-control") }}
                {% for error in form.title.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="col-sm-12 col-lg-6 form-group">
                {{ form.category_id.label }}
                <div class="d-flex justify-content-end">
                    <small>Choose a category for your question</small>
                </div>
                {{ form.category_id(class="form-control custom-select") }}
                {% for error in form.category_id.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="col-12 form-group">
                {{ form.content.label }}
                <div class="d-flex justify-content-end">
                    <small>Write your full question here, including any relevant information.</small>
                </div>
                {{ form.content(class="form-control", rows=8, value=thread.content) }}
                {% for error in form.content.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="col-12  form-group mt-4">
                {{ form.submit(class="btn btn-outline-primary w-100 btn-lg") }}
            </div>
        </div>
    </form>





{% endblock content %}

Forum/forum/apps/threads/templates/threads/show.html
{% extends "layouts/app.html" %}

{% block content %}
    <div class="container" style="justify-content: center; align-items: center;">
        <div class="row my-4" style="justify-content: center; align-items: center;">
            <div class="col-sm-12 col-lg-9 ">
                <div class="shadow-sm p-4 " style="border-radius: 5px; background-color: #efe4d4; border: 1px #b07946;">
                    <div class="d-flex justify-content-between align-items-center">
                        <h3>{{  thread.title }}</h3>
                        {% if current_user.is_authenticated and thread.is_owner(current_user) %}
                        <div class="d-flex">
                            <a href="{{ url_for('threads.edit', category_slug=thread.category.slug, thread_slug=thread.slug) }}"
                               class="btn btn-sm btn-primary mr-2"
                            >Modifier</a>
                            <form action="{{ url_for('threads.show', 
                                category_slug=thread.category.slug,
                                thread_slug=thread.slug) }}?_method=DELETE" method="POST"
                                class="form-delete"
                            >
                                <button type="submit" class="btn btn-sm btn-danger">Supprimer</button>
                            </form>
                        </div>
                        {% endif %}
                    </div>
                    <div class="d-flex align-items-center justify-content-between">
                        <small class="question-category">{{ thread.category.name }}</small>
                        <small class="text-black">Posted by {{ thread.owner.name }}</small>
                    </div>
    
                    <hr />
                    {{ thread.content }}
                </div>
                
                <comments :id="{{ thread.id }}"></comments>
            </div>
            
        </div>
    </div>

   

{% endblock content %}